# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: serverB.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='serverB.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rserverB.proto\"\x13\n\x03Req\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x12\n\x03Res\x12\x0b\n\x03log\x18\x01 \x01(\t2 \n\x06Logger\x12\x16\n\x06getLog\x12\x04.Req\x1a\x04.Res\"\x00\x62\x06proto3')
)




_REQ = _descriptor.Descriptor(
  name='Req',
  full_name='Req',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Req.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=36,
)


_RES = _descriptor.Descriptor(
  name='Res',
  full_name='Res',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='log', full_name='Res.log', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=56,
)

DESCRIPTOR.message_types_by_name['Req'] = _REQ
DESCRIPTOR.message_types_by_name['Res'] = _RES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Req = _reflection.GeneratedProtocolMessageType('Req', (_message.Message,), {
  'DESCRIPTOR' : _REQ,
  '__module__' : 'serverB_pb2'
  # @@protoc_insertion_point(class_scope:Req)
  })
_sym_db.RegisterMessage(Req)

Res = _reflection.GeneratedProtocolMessageType('Res', (_message.Message,), {
  'DESCRIPTOR' : _RES,
  '__module__' : 'serverB_pb2'
  # @@protoc_insertion_point(class_scope:Res)
  })
_sym_db.RegisterMessage(Res)



_LOGGER = _descriptor.ServiceDescriptor(
  name='Logger',
  full_name='Logger',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=58,
  serialized_end=90,
  methods=[
  _descriptor.MethodDescriptor(
    name='getLog',
    full_name='Logger.getLog',
    index=0,
    containing_service=None,
    input_type=_REQ,
    output_type=_RES,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_LOGGER)

DESCRIPTOR.services_by_name['Logger'] = _LOGGER

# @@protoc_insertion_point(module_scope)
