# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import serverB_pb2 as serverB__pb2


class LoggerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getLog = channel.unary_unary(
        '/Logger/getLog',
        request_serializer=serverB__pb2.Req.SerializeToString,
        response_deserializer=serverB__pb2.Res.FromString,
        )


class LoggerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def getLog(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_LoggerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getLog': grpc.unary_unary_rpc_method_handler(
          servicer.getLog,
          request_deserializer=serverB__pb2.Req.FromString,
          response_serializer=serverB__pb2.Res.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Logger', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
