apiVersion: apps/v1
kind: Deployment
metadata:
  name: serverb1
  labels:
    app: serverb1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serverb1
  template:
    metadata:
      labels:
        app: serverb1
    spec:
      containers:
      - name: serverb1
        image: gcr.io/dmai-logs-test/server_b1
        imagePullPolicy: Always
        ports:
          - containerPort: 50001
---

apiVersion: v1
kind: Service
metadata:
  name: serverb1
  labels:
    app: serverb1
spec:
  type: LoadBalancer
  ports:
    - targetPort: 50001
      port: 80
      protocol: TCP
  selector:
    app: serverb1
status:
  loadBalancer:
    ingress:
    - ip: 192.0.2.127
