# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import serverA_pb2 as serverA__pb2


class TimerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getTime = channel.unary_unary(
        '/Timer/getTime',
        request_serializer=serverA__pb2.Request.SerializeToString,
        response_deserializer=serverA__pb2.Response.FromString,
        )


class TimerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def getTime(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TimerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getTime': grpc.unary_unary_rpc_method_handler(
          servicer.getTime,
          request_deserializer=serverA__pb2.Request.FromString,
          response_serializer=serverA__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Timer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
